name: testcontainers documentation
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/3.10.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/3.10.txt
      - name: Build documentation
        run: make docs
      - name: Run doctests
        run: make doctests
